version: '3.8'

services:
   app:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '3000:3000'

      env_file:
         - .env.development
      depends_on:
         - mysql
      command: ['pnpm', 'run', 'start:dev']

   mysql:
      image: mysql:8.0
      environment:
         MYSQL_ROOT_PASSWORD: 123
         MYSQL_DATABASE: ecommercial_development
      ports:
         - '3306:3306'
      volumes:
         - mysql_data:/var/lib/mysql

volumes:
   mysql_data:
